#!/bin/sh
##
## ~/.bash_profile
##

# Source /etc/profile
[[ -f /etc/profile ]] && . /etc/profile

# Source .bashrc
[[ -f ~/.bashrc ]] && . ~/.bashrc

## Set CLOJURESCRIPT_HOME environment variable
export CLOJURESCRIPT_HOME="$HOME/src/github/clojurescript"

## Set LUA_INIT to load useful functions into the REPL
export LUA_INIT="@$HOME/.luarc"

## Set GITHUB_HOME to be able to use git-get and update-github
export GITHUB_HOME="$HOME/gh"

## Set GOPATH for downloading Golang packages, etc
GOPATHHOME="$HOME/rt/go"
export GOPATH="$GOPATHHOME:$GOPATH"

## Set RUBYGEM_HOME for gems with executable commands
export RUBYGEM_HOME="$HOME/.gem/ruby/2.0.0"

## local bin has highest precedence on $PATH
PATH="$HOME/bin:$GOPATHHOME/bin:$RUBYGEM_HOME/bin:$PATH"

## Set capslock to toggle kbmap
## [commented out b/c i am using xorg.conf to configure this]
#setxkbmap us,ru -option  grp:caps_toggle,grp;etc

## Set TERM var so that tmux colors work
[ -n "$TMUX" ] && export TERM=screen-256color

if [[ -z $DISPLAY && $(tty) = /dev/tty1 ]]; then
    startx
fi
