#!/bin/bash

# Disable touchpad when typing
syndaemon -t -k -i 2 -d &

# Preprocess .Xresources
xrdb -merge ~/.Xresources &

# Start Emacs server
#emacs --daemon

# Start awesome
#exec ck-launch-session awesome
exec awesome
